name: secura
version: 1.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  file_picker: ^11.0.2
  path_provider: ^2.1.3
  path: ^1.9.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^10.0.0
  secure_application: ^4.1.0
  share_plus: ^12.0.2
  gal: ^2.3.2
  open_file: ^3.5.11
  google_fonts: ^8.1.0
  animations: ^2.2.0
  crypto: ^3.0.7
  permission_handler: ^12.0.1
  font_awesome_flutter: ^11.0.0
  url_launcher: ^6.3.0
  google_sign_in: ^7.2.0
  googleapis: ^16.0.0
  googleapis_auth: ^2.3.0
  http: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  local_auth: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_brand.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/app_brand.png
    - assets/UmangGupta.png
    - assets/VineetVRao.png
    - assets/VipulKumar.png
    - assets/TribhuvanPSingh.png
    - assets/VaishnavendraDDiwvedi.png
